# The binary to build (just the basename).
BIN := myapp

# This repo's root import path (under GOPATH).
PKG := github.com/thockin/go-build-template

# Where to push the docker image.
REGISTRY ?= thockin

# Which architecture to build - see $(ALL_ARCH) for options.
ARCH ?= amd64

