name: Build all platforms

on: [ push, pull_request ]

jobs:
  crossbuild:
    strategy:
      matrix:
        go-version: [ "1.20", "1.21" ]
        platform: [ "ubuntu-latest" ]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build containers
      run: make all-container GO_VERSION=${{ matrix.go-version }}
