name: Build for all platforms

on: [ push, pull_request, workflow_dispatch ]

jobs:
  crossbuild:
    strategy:
      matrix:
        go-version: [ "1.23", "1.24" ]
        platform: [ "ubuntu-latest" ]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build containers
      run: make all-container GO_VERSION=${{ matrix.go-version }}
